In [1]:
# @title Setup
from google.colab import auth
from google.cloud import bigquery
from google.colab import data_table

project = 'data-management-landscape' # Project ID inserted based on the query results selected to explore
location = 'US' # Location inserted based on the query results selected to explore
client = bigquery.Client(project=project, location=location)
data_table.enable_dataframe_formatter()
auth.authenticate_user()

## Reference SQL syntax from the original job
Use the ```jobs.query```
[method](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/query) to
return the SQL syntax from the job. This can be copied from the output cell
below to edit the query now or in the future. Alternatively, you can use
[this link](https://console.cloud.google.com/bigquery?j=data-management-landscape:US:bquxjob_6981915e_184aa5e864e)
back to BigQuery to edit the query within the BigQuery user interface.

In [2]:
# Running this code will display the query used to generate your previous job

job = client.get_job('bquxjob_6981915e_184aa5e864e') # Job ID inserted based on the query results selected to explore
print(job.query)

NotFound: 404 GET https://bigquery.googleapis.com/bigquery/v2/projects/data-management-landscape/jobs/bquxjob_6981915e_184aa5e864e?projection=full&location=US&prettyPrint=false: Not found: Job data-management-landscape:US.bquxjob_6981915e_184aa5e864e

## Answer to Question 1

In [ ]:
project_id = 'data-management-landscape'

In [ ]:
from google.cloud import bigquery

client = bigquery.Client(project='data-management-landscape')

In [ ]:
df = client.query('''
SELECT COUNT(Source_Name), Status_Description, Discipline_Class_Desc From
(SELECT Source_Name, Status_Description, Discipline_Class_Desc  From ((
SELECT Source_Name, Status_Description,Discipline_Class_Desc  From bigquery-public-data.sdoh_hrsa_shortage_areas.hpsa_primary_care)
UNION ALL
(SELECT Source_Name, Status_Description, Discipline_Class_Desc From bigquery-public-data.sdoh_hrsa_shortage_areas.hpsa_mental_health)
UNION ALL
(SELECT Source_Name, Status_Description,Discipline_Class_Desc From bigquery-public-data.sdoh_hrsa_shortage_areas.hpsa_dental_health
) ) )
GROUP BY Status_Description, Discipline_Class_Desc;

''').to_dataframe()
df

     f0_       Status_Description Discipline_Class_Desc
0  13965                Withdrawn         Dental Health
1  16526               Designated         Dental Health
2    155  Proposed For Withdrawal         Dental Health
3   9068                Withdrawn         Mental Health
4  15317               Designated         Mental Health
5     67  Proposed For Withdrawal         Mental Health
6  22489               Designated          Primary Care
7    195  Proposed For Withdrawal          Primary Care
8  34032                Withdrawn          Primary Care

In [ ]:
df.to_csv("question1_query_result.csv", index=False)

In [ ]:
df = df.copy()

In [ ]:
import plotly.express as px
import plotly.graph_objects as go

In [ ]:
df.f0_

0    13965
1    16526
2      155
3     9068
4    15317
5       67
6    22489
7      195
8    34032
Name: f0_, dtype: Int64

In [ ]:
subdata = df[['f0_', 'Status_Description', 'Discipline_Class_Desc']]
# subdata = subdata.groupby(['Status_Description']).count().reset_index(drop=False)  #do the same in sql
# subdata = subdata.reset_index(drop=False)
# subdata = subdata[[col1,col2,'']]
subdata.columns = ['Counts','Status',"Class"]
subdata

   Counts                   Status          Class
0   13965                Withdrawn  Dental Health
1   16526               Designated  Dental Health
2     155  Proposed For Withdrawal  Dental Health
3    9068                Withdrawn  Mental Health
4   15317               Designated  Mental Health
5      67  Proposed For Withdrawal  Mental Health
6   22489               Designated   Primary Care
7     195  Proposed For Withdrawal   Primary Care
8   34032                Withdrawn   Primary Care

In [ ]:
fig2 = px.bar(subdata, x='Status',y='Counts',color='Class', title='Overall HPSA Status counts of various classes')
fig2

#Answer to Question 2

In [ ]:
df = []
subdata = []
df = client.query('''
SELECT HPSA_Score, State_Name, Discipline_Class_Desc From ((
SELECT HPSA_Score, State_Name,Discipline_Class_Desc  From bigquery-public-data.sdoh_hrsa_shortage_areas.hpsa_primary_care)
UNION ALL
(SELECT HPSA_Score, State_Name,Discipline_Class_Desc From bigquery-public-data.sdoh_hrsa_shortage_areas.hpsa_mental_health)
UNION ALL
(SELECT HPSA_Score, State_Name,Discipline_Class_Desc From bigquery-public-data.sdoh_hrsa_shortage_areas.hpsa_dental_health
) ) WHERE HPSA_Score IS NOT NULL
''').to_dataframe()
df

Warning: total number of rows (111814) exceeds max_rows (20000). Falling back to pandas display.

        HPSA_Score     State_Name Discipline_Class_Desc
0               12  Massachusetts         Mental Health
1               16        Vermont         Mental Health
2               16        Vermont         Mental Health
3               16        Vermont         Mental Health
4               16        Vermont         Mental Health
...            ...            ...                   ...
111809          11      Wisconsin          Primary Care
111810          11      Wisconsin          Primary Care
111811          11      Wisconsin          Primary Care
111812          11      Wisconsin          Primary Care
111813          11      Wisconsin          Primary Care

[111814 rows x 3 columns]

In [ ]:
subdata = df.copy()

In [ ]:
subdata = df[['State_Name', 'HPSA_Score','Discipline_Class_Desc']]
subdata = subdata.groupby(['State_Name', 'Discipline_Class_Desc']).mean().round().reset_index(drop=False)
# subdata = subdata.groupby(['State_Name']).count().reset_index(drop=False)
# subdata = subdata.reset_index(drop=False)
# subdata = subdata[[col1,col2,'']]
subdata.columns = ['State_Name','Class','HPSA_Score']
subdata

NameError: name 'df' is not defined

In [ ]:
df.to_csv("question2_query_result.csv", index=False)

In [ ]:
fig1 = px.bar(subdata, x='State_Name', y='HPSA_Score',color='Class', title="HPSA Score for areas of various classes")
fig1